
EPOCH 1:
Traceback (most recent call last):
  File "/Users/xanderdavies/Desktop/normout/runner.py", line 91, in <module>
    avg_loss, avg_acc = train_one_epoch(epoch_number)
  File "/Users/xanderdavies/Desktop/normout/runner.py", line 55, in train_one_epoch
    wandb.log("Loss/train", last_loss, tb_x)
  File "/Users/xanderdavies/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1422, in log
    self._log(data=data, step=step, commit=commit)
  File "/Users/xanderdavies/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1198, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary