
EPOCH 1:
Traceback (most recent call last):
  File "/Users/xanderdavies/Desktop/normout/runner.py", line 93, in <module>
    avg_loss, avg_acc = train_one_epoch(epoch_number)
  File "/Users/xanderdavies/Desktop/normout/runner.py", line 67, in train_one_epoch
    wandb.log({"Train Accuracy", num_correct / num_total})
  File "/Users/xanderdavies/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1422, in log
    self._log(data=data, step=step, commit=commit)
  File "/Users/xanderdavies/opt/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1198, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary